name: build image

on:
  push:
    branches: master
    
jobs:
  publish:
    name: Publish Image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Preparation
      id: prep
      run: |
        REGISTRY="ghcr.io"
        IMAGE="${REGISTRY}/${{ github.event.repository.name }}"
        SHA="${{ github.sha }}"
        TAGS="${IMAGE,,}:${SHA:0:6}"
        TAGS="${TAGS},${IMAGE,,}:latest"
        echo ::set-output name=tags::${TAGS}
    - name: Docker Buildx setup
      uses: docker/setup-buildx-action@v1
    - name: Login in to registry
      uses: docker/login-action@v1
      with:
        registry: docker.pkg.github.com
        username: ${{ secrets.repository_owner }}
        password: ${{ secrets.CR_PAT }}
    - name: Push to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        file: ./dockerfile.prod
        tags: ${{ steps.prep.outputs.tags }}
